spring:
datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 1234
  driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect
main:
  allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    hw40: INFO
    org.springframework.web: INFO
